version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: ubuntu
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 120
      runas: ubuntu
